# Generated by Django 5.2 on 2025-04-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('sponsors', 'Для спонсоров'), ('investors', 'Для инвесторов')], default='investors', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='Не указано', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(blank=True, default='Не указан', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(default='Опишите ваш проект подробно цели, задачи, этапы реализации, команда'),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=6, help_text='Срок реализации в месяцах'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Описание проекта отсутствует'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='Без названия', max_length=255),
        ),
    ]
