# Generated by Django 5.2 on 2025-04-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='required_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='roi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
