# Generated by Django 5.2 on 2025-05-07 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='date_subscribed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
